Sliding window improvements
scverse/squidpy pull request #931
Opened 2024-12-25 14:36 UTC by mossishahi

**IMPORTANT: Please search among the [Pull requests](../pulls) before creating one.**

## Description

## How has this been tested?

## Closes

2025-02-21 14:47 UTC, FrancescaDr commented on src/squidpy/tl/_sliding_window.py
> +    assert max_n_cells is None or n_splits is None, (
Also: assert that not all `window_size`, `max_n_cells` and `n_splits` are `None`.

2025-02-21 15:07 UTC, FrancescaDr requested changes
Hi @mossishahi, thanks for the implementation. Please don't forget to add tests for all the functions that you added. I also recommend to check out the [squidpy contribution](https://github.com/scverse/squidpy/blob/main/CONTRIBUTING.rst) guidelines to make sure the code and docstrings are correctly formatted.

2025-02-21 15:07 UTC, FrancescaDr commented on src/squidpy/tl/_sliding_window.py
>      if overlap == 0:
Also enable drop_partial_windows for the case of no overlap.

2025-02-21 15:07 UTC, FrancescaDr commented on src/squidpy/tl/_sliding_window.py
> +    """
Adjust doctoring to squidpy/scverse style guide.

2025-02-21 17:03 UTC, FrancescaDr commented on src/squidpy/tl/_sliding_window.py
> +    window_size: int
Overall there are some function parameters that are not described in the doctoring. Please make sure to include documentation for all.

2026-08-12 22:40 UTC, timtreis commented
Closing in favour of https://github.com/scverse/squidpy/pull/1116

2026-08-12 22:40 UTC, closed without merging